import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/space-grotesk/latin-400.css';
import '@fontsource/space-grotesk/latin-500.css';
import '@fontsource/space-grotesk/latin-700.css';
import { siteConfig } from './site-config.js';

const arrow = '<span aria-hidden="true"><svg width="17" height="17" viewBox="0 0 24 24" fill="none"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.7"/></svg></span>';
const banana = `<svg viewBox="0 0 60 60" fill="none" aria-hidden="true"><path d="M45 8c3 20-6 33-27 34-6 1-10-1-13-4 5 11 14 17 26 13C49 45 55 24 48 8Z" fill="currentColor"/><path d="m44 6 5-1 2 7-6 2Z" fill="currentColor"/><path d="M11 40c15 4 30-6 35-21" stroke="#11120f" stroke-width="2"/></svg>`;
const brand = `<a href="/" class="brand" aria-label="BananaZone home">${banana}<span>BANANA<span class="brand-light">ZONE</span><small>GAMES</small></span></a>`;
const partner = `<a class="partner" href="https://jackpot.bet" target="_blank" rel="noopener noreferrer" aria-label="Jackpot Studios, visit Jackpot.bet"><span class="partner-mark" aria-hidden="true">✳</span><span>JACKPOT<small>STUDIOS</small></span></a>`;

function landing() {
document.querySelector('#app').innerHTML = `
  <header class="nav wrap">${brand}<nav aria-label="Main navigation"><a href="#game">The game</a><a href="#operators">For operators</a><a href="#integration">Integration</a></nav><a class="button small outline" href="#contact">Let’s talk ${arrow}</a></header>
  <main>
    <section class="hero wrap">
      <div class="hero-copy"><h1>A new kind<br>of <span class="yellow">play</span></h1><p>Tap into something different. A fresh casino mechanic that brings the energy of trading to a game built for your players.</p><div class="actions"><a class="button" href="#game">Explore the game ${arrow}</a><a class="text-link" href="#contact">Talk integration <span>→</span></a></div><div class="hero-partner"><span>DEVELOPED IN PARTNERSHIP WITH</span>${partner}</div></div>
      <div class="hero-visual"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="floating-tag tag-top">YOUR NEXT<br><strong>LOBBY ORIGINAL.</strong></div><div class="hero-screen"><div class="screen-bar"><span>● ● ●</span><span>ONE MECHANIC. ENDLESS PERSONALITY.</span></div><img src="/assets/candy.png" alt="Candy Zone game design with a purple target grid and yellow index chart" fetchpriority="high"></div><div class="floating-tag tag-bottom"><span>↗</span> TAP. CONFIRM.<br><strong>WATCH IT PLAY OUT.</strong></div><div class="visual-caption">A FICTIONAL INDEX. A REAL NEW GAME MECHANIC.</div></div>
    </section>
    <div class="ticker" aria-label="Tap trading. Built for casinos. Made to stand out. A collaboration between BananaZone Games and Jackpot Studios."><div class="ticker-track">${[false, true].map(hidden => `<div class="ticker-group"${hidden ? ' aria-hidden="true"' : ''}><span>TAP TRADING</span><i aria-hidden="true">✳</i><span>BUILT FOR CASINOS</span><i aria-hidden="true">✳</i><span>MADE TO STAND OUT</span><i aria-hidden="true">✳</i><span>A collaboration between BananaZone Games and Jackpot Studios</span><i aria-hidden="true">✳</i></div>`).join('')}</div></div>
    <section class="intro wrap" id="operators"><div class="eyebrow">SOMETHING DIFFERENT</div><div class="intro-grid"><h2>Your lobby has slots,<br>it has crash and plinko<br><span class="muted">Now give it</span> <span class="yellow">tap trading</span></h2><div><p class="large-copy">Familiar trading energy.<br>A fresh way to play.</p><p>BananaZone brings a new game format to your casino floor. Players choose where a moving index will land, tap to confirm and watch the results unfold in 3 second rounds.</p><p>A distinctive addition for operators looking beyond the usual lobby line-up. No market feeds. No trading accounts. Just a provably fair RNG-driven index and an easy to use tap-to-play mechanic.</p><a href="#game" class="text-link">See it in action <span>↓</span></a></div></div><div class="benefits"><div><span class="benefit-icon">⌁</span><h3>A fresh mechanic</h3><p>Give players something to discover beyond familiar casino formats.</p></div><div><span class="benefit-icon">◎</span><h3>Single or double tap</h3><p>Offer your players a single or double tap mechanism, for faster or safer betting.</p></div><div><span class="benefit-icon">▧</span><h3>Your brand, your game</h3><p>Customisable core game mechanic that can be skinned to your casino’s identity or special event.</p></div></div></section>
    <section class="game-section" id="game"><div class="wrap"><div class="section-heading"><div><div class="eyebrow">MEET YOUR NEXT ORIGINAL</div><h2>Same game<br><span class="yellow">Different flavour</span></h2></div><p>Offer your players tap trading classic or turn up the personality and skin the game to feel at home in your lobby.</p></div><div class="game-cards"><article class="game-card"><div class="card-top"><span class="pill">THE ORIGINAL</span><span class="card-number">01</span></div><a href="/demo.html?skin=base" class="game-image" data-demo="base" aria-label="Explore the dark edition demo"><img src="/assets/base.png" alt="Dark unskinned BananaZone game concept with target multipliers and a moving index" loading="lazy"><span class="image-play" aria-hidden="true">↗</span></a><div class="card-copy"><h3>Dark. Clean. Ready for you.</h3><p>The neutral base. An understated look that puts the mechanic front and centre.</p></div><a href="/demo.html?skin=base" class="button outline full" data-demo="base">Play the demo <span>▶</span></a></article><article class="game-card candy-card"><div class="card-top"><span class="pill purple">CANDY ZONE</span><span class="card-number">02</span></div><a href="/demo.html?skin=candy" class="game-image" data-demo="candy" aria-label="Explore the Candy Zone demo"><img src="/assets/candy.png" alt="Candy Zone designed edition with purple moulded tiles, yellow chart and mint accents" loading="lazy"><span class="image-play" aria-hidden="true">↗</span></a><div class="card-copy"><h3>A little more a-peel.</h3><p>Bold colour. Playful surfaces. A game with a personality players can spot at a glance.</p></div><a href="/demo.html?skin=candy" class="button full" data-demo="candy">Play the demo <span>▶</span></a></article></div></div></section>
    <section class="tech wrap" id="integration"><div class="section-heading"><div><div class="eyebrow">BUILT FOR YOUR BUSINESS</div><h2>Fresh on the front<br><span class="muted">Solid underneath</span></h2></div><p>Developed with Jackpot Studios, our standalone tap-trading casino edition is built, hosted and supported on their remote gaming server by a team with years of experience in igaming and casino implementation.</p></div><div class="tech-grid"><article><span class="tech-icon">◈</span><h3>Certified RNG game system</h3><p>A fictional Banana Index generated by our game system, with verified game maths and RTP configurations.</p></article><article><span class="tech-icon">↻</span><h3>Provably fair by design</h3><p>Seed-based outcomes designed to be reproducible and player-verifiable through the provider’s verification scheme.</p></article><article><span class="tech-icon">▣</span><h3>Responsive infrastructure</h3><p>Responsive play across mobile, tablet and desktop. No app download or live market data dependency.</p></article><article><span class="tech-icon">⇄</span><h3>RGS-led integration</h3><p>Operator sessions, balance, currency and limits connect through Jackpot Studios’ remote gaming server.</p></article><article><span class="tech-icon">▥</span><h3>Operator visibility</h3><p>Betting and exposure controls, with game events covering wagering, repeat play, session length and drop-off.</p></article><article><span class="tech-icon">✳</span><h3>Support included</h3><p>Hosting, monitoring, maintenance and release operations managed by Jackpot Studios.</p></article></div><p class="technical-note">Certification refers to the provider’s internal game-system, maths and RNG certification and requirements under its Anjouan B2B licence. Jurisdiction-specific third-party certification is separately scoped. Availability depends on operator and territory eligibility.</p></section>
    <section class="launch wrap"><div class="launch-time"><span class="eyebrow">LESS WAIT. MORE PLAY.</span><span class="big-number">&lt; 2 <small>WEEKS</small></span><p>For operators and aggregators. From integration sign-off to launch.*</p></div><div class="launch-content"><h2>A new game<br>A quick way in</h2><p>We work with operators and aggregators to get BananaZone into your lobby quickly, with a clear path from technical fit to launch.</p><ol><li><span>01</span><div><strong>Let’s find the fit</strong><small>Review your platform, markets and preferred look.</small></div></li><li><span>02</span><div><strong>Connect & validate</strong><small>RGS integration, wallet checks and platform testing.</small></div></li><li><span>03</span><div><strong>Bring it to your lobby</strong><small>Agree launch readiness and go live.</small></div></li></ol><p class="fine-print">*Target for operator and aggregator integration of the release-ready game, subject to technical readiness, approvals and jurisdiction requirements.</p></div></section>
    <section class="faq wrap"><div><div class="eyebrow">A FEW GOOD QUESTIONS</div><h2>Let’s clear<br>things up</h2></div><div class="faq-items"><details><summary>Is this trading on real financial markets?<span>+</span></summary><p>No. The Banana Index is fictional and random, generated by the game system. There are no real assets, live market feeds or price oracles.</p></details><details><summary>Can we use our own casino branding?<span>+</span></summary><p>Yes. The scope includes a brandable skin for operator re-theming. We’ll discuss your preferred treatment and agree the design scope before integration.</p></details><details><summary>Who handles hosting and the game backend?<span>+</span></summary><p>Jackpot Studios manages the game implementation, maths and RNG, RGS integration, hosting, security, monitoring, support and maintenance.</p></details><details><summary>Which RTP and jurisdictions are available?<span>+</span></summary><p>RTP configurations and market eligibility are confirmed with Jackpot Studios for each deployment. This edition is not offered as universally certified; additional jurisdiction-specific testing is a separate scope.</p></details><details><summary>Can we try it before discussing integration?<span>+</span></summary><p>Absolutely. Explore either treatment above. Until the official operator demo is connected, these links open a clearly labelled interactive concept using simulated demo credits.</p></details></div></section>
    <section class="contact-section" id="contact"><div class="wrap contact-inner"><div class="eyebrow">YOUR NEXT ORIGINAL STARTS HERE</div><h2>Let’s put something<br><span>different</span> in your lobby</h2><p>Operator or aggregator? Contact us for more information integration,<br>ask a question, or book a call with the BananaZone team.</p><div class="actions"><button class="button dark" data-contact="booking">Book a call ${arrow}</button><button class="button transparent" data-contact="email">Contact us for more information ${arrow}</button></div></div></section>
  </main><footer class="wrap"><div>${brand}<p>A fresh perspective on casino play.</p></div><div class="footer-right"><span>© ${new Date().getFullYear()} BananaZone Games</span><span>For casino operators & aggregators · 18+</span><a href="#integration">Territory and certification details ↑</a></div></footer>
  <dialog id="contact-dialog"><button class="dialog-close" aria-label="Close dialog">×</button><div class="eyebrow">LET’S CONNECT</div><h2 id="dialog-title"></h2><p id="dialog-copy"></p><button class="button" id="dialog-back">Back to the page →</button></dialog>`;
document.querySelectorAll('[data-demo]').forEach(a => { const url = siteConfig.demoUrls[a.dataset.demo]; if (url) { a.href = url; a.target = '_blank'; a.rel = 'noopener noreferrer'; } });
if (siteConfig.partnerLogoUrl) document.querySelectorAll('.partner').forEach(a => { a.innerHTML = ''; const img = new Image(); img.src = siteConfig.partnerLogoUrl; img.alt = 'Jackpot Studios'; a.append(img); });
document.querySelectorAll('[data-contact]').forEach(button => button.addEventListener('click', () => {
const booking = button.dataset.contact === 'booking';
const url = booking ? siteConfig.calendlyUrl : siteConfig.contactEmail ? `mailto:${siteConfig.contactEmail}?subject=BananaZone%20casino%20integration` : '';
if(url) { if(booking) window.open(url, '_blank', 'noopener,noreferrer'); else window.location.href = url; return; }
document.querySelector('#dialog-title').textContent = booking ? 'Booking opens soon' : 'Let’s talk BananaZone';
document.querySelector('#dialog-copy').textContent = booking ? 'The team’s Calendly link hasn’t been connected to this preview yet. Please contact your BananaZone representative to arrange a call.' : 'The enquiry address hasn’t been connected to this preview yet. Please reach out to your BananaZone representative with your platform and integration questions.';
document.querySelector('#contact-dialog').showModal();
}));
document.querySelectorAll('.dialog-close, #dialog-back').forEach(b => b.addEventListener('click', () => document.querySelector('#contact-dialog').close()));
}

function demo() {
const skin = new URLSearchParams(location.search).get('skin') === 'candy' ? 'candy' : 'base';
const external = siteConfig.demoUrls[skin];
if (external) { location.replace(external); return; }
document.querySelector('#app').innerHTML = `<header class="nav wrap">${brand}<a class="text-link" href="/#game">← Back to the game</a></header><main class="demo-page wrap ${skin}"><div class="eyebrow">INTERACTIVE CONCEPT · NO REAL MONEY</div><h1>${skin === 'candy' ? 'Candy Zone' : 'The dark original'}</h1><p class="demo-disclaimer">An illustrative tap-trading experience for operators. This is not the Jackpot Studios game, a certified RNG demo, or a simulation of final game maths. All credits and outcomes below are for presentation only.</p><div class="demo-toolbar"><span>DEMO CREDITS <strong id="balance">1,000</strong></span><label>Stake <select id="stake"><option>5</option><option selected>10</option><option>25</option></select></label><a href="/demo.html?skin=${skin === 'candy' ? 'base' : 'candy'}">Try ${skin === 'candy' ? 'dark' : 'Candy Zone'} →</a></div><div class="demo-board"><div class="demo-board-head"><span>🍌 BANANA INDEX</span><span>ILLUSTRATIVE 5-SECOND ROUND</span></div><div class="demo-chart"><svg viewBox="0 0 800 170" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#e8fa55" stop-opacity=".25"/><stop offset="1" stop-color="#e8fa55" stop-opacity="0"/></linearGradient></defs><path d="M0 100 35 110 70 80 105 95 140 65 175 100 210 70 245 50 280 75 315 45 350 60 385 100 420 75 455 85 490 50 525 65 560 40 595 55 630 25 665 45 700 20 735 45 770 25 800 35 V170 H0Z" fill="url(#fill)"/><path d="M0 100 35 110 70 80 105 95 140 65 175 100 210 70 245 50 280 75 315 45 350 60 385 100 420 75 455 85 490 50 525 65 560 40 595 55 630 25 665 45 700 20 735 45 770 25 800 35" fill="none" stroke="#e8fa55" stroke-width="3"/></svg></div><p class="demo-help">Pick a landing band, then tap the same band again to confirm.</p><div class="demo-targets">${['Upper band','Centre band','Lower band'].map((name,i) => `<button class="target" data-band="${i}"><span>${name}</span><strong>2.00×</strong><small>Tap to select</small></button>`).join('')}</div><div id="demo-status" role="status" aria-live="polite">Choose a target to begin. Outcomes are illustrative.</div></div><div class="demo-bottom"><button class="button outline" id="reset">Reset demo</button><a class="button" href="/#contact">Discuss integration ${arrow}</a></div><p class="fine-print">A deliberately simplified concept with three bands and fixed example multipliers. The production specification uses 17 bands per settlement column, with certified game maths. No accounts, deposits or financial transactions.</p></main>`;
let armed = null, busy = false, balance = 1000, expiry, settlement;
const status = document.querySelector('#demo-status');
const targets = [...document.querySelectorAll('.target')];
function clearTargets() { targets.forEach(b => { b.classList.remove('selected','won','lost'); b.querySelector('small').textContent = 'Tap to select'; b.disabled = false; }); }
function drawBalance() { document.querySelector('#balance').textContent = balance.toLocaleString(); }
targets.forEach(b => b.addEventListener('click', () => {
if(busy) return;
const stake = Number(document.querySelector('#stake').value);
if(balance < stake) { status.textContent = 'Not enough demo credits. Reset the demo to continue.'; return; }
if(armed !== b) { clearTimeout(expiry); clearTargets(); armed = b; b.classList.add('selected'); b.querySelector('small').textContent = 'Tap again to confirm'; status.textContent = `${b.querySelector('span').textContent}: ${stake} demo credits. Example total return: ${stake * 2}. Confirm within 3 seconds.`; expiry = setTimeout(() => { armed = null; clearTargets(); status.textContent = 'Selection expired. No credits deducted. Pick a band to try again.'; },3000); return; }
clearTimeout(expiry); armed = null; busy = true; balance -= stake; drawBalance(); document.querySelector('#stake').disabled = true; targets.forEach(t => {t.disabled = true;}); b.querySelector('small').textContent = 'Confirmed'; let count = 5; status.textContent = `Confirmed. Illustrative settlement in ${count} seconds…`;
settlement = setInterval(() => {count--; if(count > 0) {status.textContent = `Confirmed. Illustrative settlement in ${count} seconds…`; return; } clearInterval(settlement); const result = Math.floor(Math.random() * 3); const win = result === Number(b.dataset.band); if(win) balance += stake * 2; drawBalance(); b.classList.add(win ? 'won' : 'lost'); targets[result].classList.add('won'); status.textContent = `Index landed in ${targets[result].querySelector('span').textContent.toLowerCase()}. ${win ? `Won: ${stake * 2} demo credits returned.` : `Lost: ${stake} demo credits.`} This result is illustrative. Pick a new target to play again.`; busy = false; targets.forEach(t => t.disabled = false); document.querySelector('#stake').disabled = false; },1000);
}));
document.querySelector('#stake').addEventListener('change', () => {clearTimeout(expiry); armed = null; clearTargets(); status.textContent = 'Stake updated. Pick a target to begin.';});
document.querySelector('#reset').addEventListener('click', () => {clearTimeout(expiry);clearInterval(settlement); armed = null; busy = false; balance = 1000; drawBalance(); clearTargets(); document.querySelector('#stake').disabled = false; status.textContent = 'Demo reset. Choose a target to begin.';});
}
if(location.pathname === '/demo.html') demo(); else landing();
